name: Config cache reload
run-name: Force config cache reload on ${{ inputs.proxy }}
on: 
  workflow_dispatch:
    inputs:
      proxy:
        description: Zabbix proxy name
        type: choice
        options:
          - zabbix-proxy-sp
          - zabbix-proxy-rj

jobs:
  config_cache_reload:
    runs-on: ${{ inputs.proxy }}
    steps:
      - name: Show info vm
        run: |
          default_ip=$(ip r |grep default | awk '{print $3}')
          echo $HOSTNAME - $default_ip
      - name: Reload cache
        run: |
          zabbix_proxy -R config_cache_reload
      - name: Check log
        run: |
          tail -n 20 /var/log/zabbix/zabbix_proxy.log