name: Config cache reload
run-name: Config
on: workflow_dispatch

inputs:
  proxy:
    type: choice
    description: Zabbix proxy name
    options:
      - zabbix-proxy-sp
      - zabbix-proxy-rj

jobs:
  config_cache_reload:
    runs-on: ${{ inputs.proxy }}
    steps:
      - name: Reload cache
        run: |
          zabbix_proxy -R config_cache_reload
      - name: Check log
        run: |
          tail -n 20 /var/log/zabbix/zabbix_proxy.log